name: multiomics-biomarker-discovery
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - pyviz

dependencies:
  # Core Python
  - python=3.11
  
  # Core Data Processing
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  
  # Machine Learning
  - scikit-learn>=1.3.0
  - xgboost>=1.7.0
  - lightgbm>=3.3.0
  
  # Deep Learning
  - pytorch>=2.0.0
  - pytorch-lightning>=2.0.0
  
  # Bioinformatics (from bioconda)
  - biopython>=1.81
  
  # Statistical Analysis
  - statsmodels>=0.14.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  - bokeh>=3.2.0
  
  # Network Analysis
  - networkx>=3.1
  - python-igraph>=0.10.0
  
  # Development Tools
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0
  
  # File I/O
  - h5py>=3.9.0
  - pytables>=3.8.0
  - openpyxl>=3.1.0
  
  # Web and APIs
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  
  # Parallel Processing
  - joblib>=1.3.0
  - dask>=2023.6.0
  
  # Configuration
  - pyyaml>=6.0
  
  # Progress and CLI
  - tqdm>=4.65.0
  - click>=8.1.0
  
  # Scientific Computing
  - numba>=0.57.0
  
  # Dimensionality Reduction
  - umap-learn>=0.5.3
  
  # Database
  - sqlalchemy>=2.0.0
  
  # Memory and Profiling
  - psutil>=5.9.0
  
  # Image Processing
  - pillow>=10.0.0
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    # Specialized Bioinformatics
    - pybiomart>=0.2.0
    - mygene>=3.2.0
    - gprofiler-official>=1.0.0
    
    # Pathway Analysis
    - gseapy>=1.0.0
    - enrichr>=3.0
    
    # Advanced Statistics
    - pingouin>=0.5.0
    - lifelines>=0.27.0
    
    # Model Interpretation
    - shap>=0.42.0
    - lime>=0.2.0
    - eli5>=0.13.0
    
    # Hyperparameter Optimization
    - optuna>=3.2.0
    - hyperopt>=0.2.7
    
    # Data Validation
    - pydantic>=2.0.0
    - cerberus>=1.3.4
    
    # Configuration Management
    - python-dotenv>=1.0.0
    - hydra-core>=1.3.0
    
    # Logging and Monitoring
    - loguru>=0.7.0
    - wandb>=0.15.0
    - mlflow>=2.4.0
    
    # Advanced Testing
    - pytest-cov>=4.1.0
    - pytest-mock>=3.11.0
    - hypothesis>=6.80.0
    
    # Code Quality
    - mypy>=1.4.0
    - isort>=5.12.0
    
    # Documentation
    - sphinx>=7.0.0
    - sphinx-rtd-theme>=1.3.0
    - nbsphinx>=0.9.0
    
    # Interactive Widgets
    - ipywidgets>=8.0.0
    
    # Web Framework
    - dash>=2.10.0
    - dash-bootstrap-components>=1.4.0
    
    # Cloud Storage
    - boto3>=1.28.0
    - google-cloud-storage>=2.10.0
    - azure-storage-blob>=12.17.0
    
    # Workflow Management
    - snakemake>=7.30.0
    - prefect>=2.10.0
    
    # Advanced ML
    - catboost>=1.2.0
    - transformers>=4.30.0
    - imbalanced-learn>=0.11.0
    - combo>=0.1.3
    
    # Survival Analysis
    - scikit-survival>=0.21.0
    - pycox>=0.2.3
    
    # Feature Selection
    - scikit-feature>=1.1.0
    - boruta>=0.3.0
    
    # Network Visualization
    - pyvis>=0.3.2
    
    # Development Tools
    - pre-commit>=3.3.0
    - cookiecutter>=2.2.0
    - docker>=6.1.0
    
    # Caching and Performance
    - diskcache>=5.6.0
    - redis>=4.6.0
    - memory-profiler>=0.61.0
    - line-profiler>=4.1.0
    
    # Time Series
    - tslearn>=0.6.0
    - sktime>=0.21.0
    
    # Configuration Validation
    - jsonschema>=4.18.0
    - marshmallow>=3.20.0
    
    # CLI Enhancement
    - rich>=13.4.0
    - typer>=0.9.0
    
    # Additional Scientific
    - polars>=0.18.0
    - scikit-learn-extra>=0.3.0
    - aiohttp>=3.8.0
    - opencv-python>=4.8.0
    - xlrd>=2.0.0
    - ray>=2.5.0
    - py-spy>=0.3.14
    - cython>=3.0.0
    - psycopg2-binary>=2.9.0
    - pymongo>=4.4.0